console.log (typeof 42)
console.log (typeof 'Veinticinco')
console.log (-666)
console.log (true)
console.log (0)
console.log ('')
console.log (null)
console.log (undefined)
console.log (FALSE)
console.log ("omar")
console.log (1+2)